# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1f2f5e7301e001f6621f7cb902f150173d2a82dae68042b962b29d36504bf54bc982344b7576fec1340eca0b9a52daa5922a6284c3d58d9bc8b0e14d6dfe1035

test:
  secret_key_base: 33a71cd32294a329c285796c8eceb1e0bb2f00844bd1c8bd44f0fbf2ef3d385466abcd7577f57958328d5cf3927544e0197300b3ad1d4e0891dc86ff9a94df9b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
